---
title: BCI versus Luquillo
subtitle: Comparing columns between datasets
---

# Data

Loading the data from BCI that I have.

```{r}
library(fgeo.data)
```

Creating tables from luquillo.

```{r}
# rtbl::rtbl(
#   luquillo::ViewFullTable_luquillo,
#   luquillo::ViewTaxonomy_luquillo,
#   plotname = "luquillo"
# )
```

# Tree

Comparing columns between datasets.

```{r}
load(here::here("full/luquillo.full6.rdata"))
luquillo_tree <- luquillo.full6
bci_tree <- fgeo.data::bci_tree6_random

# Not in Luquillo
setdiff(
  names(bci_tree),
  names(luquillo_tree)
)

# Not in bci
setdiff(
  names(luquillo_tree),
  names(bci_tree)
)
```

# Stem

Comparing columns between datasets.

```{r}
load(here::here("stem/luquillo.stem6.rdata"))
luquillo_stem <- luquillo.stem6
bci_stem <- fgeo.data::bci_stem6_random

# Not in Luquillo
setdiff(
  names(bci_stem),
  names(luquillo_stem)
)

# Not in bci
setdiff(
  names(luquillo_stem),
  names(bci_stem)
)
```

# Data dictionary

From http://ctfs.si.edu/Public/DataDict/data_dict.php.

```{r}
DT::datatable(data_dictionary)
```
